"""Human-readable catalog of the playbook setups (src/docs/10-VOLUME-PROFILE-PLAYBOOK.md, Part 3)."""

from __future__ import annotations

GROUPS = {
    "A": "Imbalance / trend - buy options",
    "B": "Rejection / failed breakout - return to value",
    "C": "Balance / rotational - sell defined-risk premium",
    "D": "Expiry-day behaviour",
}

SETUPS: list[dict[str, str]] = [
    {"id": "A1", "group": "A", "name": "Open Drive trend day",
     "context": "Open outside prior value and drive away without returning to the open.",
     "trigger": "First 15-min candle closes in the drive direction; enter on a break of its extreme.",
     "strategy": "Buy ATM / one-strike-ITM CE or PE.",
     "stop": "Futures back through the opening price, or premium -30-35%.",
     "targets": "1x IB extension, then 2x IB or next HVN; trail as DPOC migrates."},
    {"id": "A2", "group": "A", "name": "Open Test Drive",
     "context": "Open tests a reference (prior VAH/VAL/POC/high/low), finds no business, drives the other way.",
     "trigger": "Price reverses from the test and crosses back through the opening price.",
     "strategy": "Buy ATM / one-strike-ITM in the drive direction.",
     "stop": "Beyond the test extreme, or premium -30%.",
     "targets": "Opposite side of the IB, then 1.5-2x IB or prior extreme."},
    {"id": "A3", "group": "A", "name": "IB breakout / Normal Variation",
     "context": "Narrow-to-average IB, then a one-sided extension with DPOC shifting toward it.",
     "trigger": "A 30-min period closes beyond the IB extreme.",
     "strategy": "Buy ATM; debit spread if the IB is already above average.",
     "stop": "Back inside the IB by more than 25% of its range.",
     "targets": "1.5x IB (book half), 2x IB."},
    {"id": "A4", "group": "A", "name": "Balance-area breakout",
     "context": "3-7 sessions of overlapping value; price breaks out and builds value outside.",
     "trigger": "30-min close beyond the composite edge plus a retest that holds.",
     "strategy": "Intraday ATM option; positional debit spread / ITM.",
     "stop": "Two 30-min periods back inside the composite value area.",
     "targets": "Half and full measured move (balance height)."},
    {"id": "A5", "group": "A", "name": "Single-print continuation",
     "context": "A trend or double-distribution day left single prints between two value zones.",
     "trigger": "Pullback into the top of the single prints is rejected.",
     "strategy": "Buy ATM in the trend direction.",
     "stop": "Single prints filled completely.",
     "targets": "Retest of the extreme, then 2x IB."},
    {"id": "B1", "group": "B", "name": "Open Rejection Reverse / failed gap",
     "context": "Gap outside prior value, early move further away is rejected (tail or delta divergence).",
     "trigger": "15-min close back through the open and inside the prior day's range.",
     "strategy": "Debit spread (gap IV is inflated) or ATM option toward value.",
     "stop": "Beyond the rejected extreme.",
     "targets": "Prior VA edge, prior POC, opposite edge if the 80% rule activates."},
    {"id": "B2", "group": "B", "name": "80% rule",
     "context": "Open outside prior value, then two consecutive 30-min periods back inside it.",
     "trigger": "Close of the second 30-min period inside value, with DPOC accepted into value.",
     "strategy": "Debit spread with the short strike near the opposite edge.",
     "stop": "30-min close back outside value.",
     "targets": "Prior POC (half), opposite value edge."},
    {"id": "B3", "group": "B", "name": "Failed IB breakout",
     "context": "Price looks beyond the IB but cannot build value outside it.",
     "trigger": "30-min close back inside the IB after a failed extension.",
     "strategy": "Buy ATM in the fade direction (or credit spread beyond the failed extreme).",
     "stop": "Beyond the failed breakout extreme.",
     "targets": "IB midpoint, then the opposite IB extreme."},
    {"id": "B4", "group": "B", "name": "Poor high/low repair",
     "context": "Prior session left a flat extreme with no tail (unfinished business).",
     "trigger": "Initiative 30-min period toward the poor extreme.",
     "strategy": "Small ATM buy (half size).",
     "stop": "Behind the initiating period.",
     "targets": "Just beyond the poor extreme."},
    {"id": "C1", "group": "C", "name": "Open inside value - iron condor",
     "context": "Open inside prior value and range; IB forms inside prior value and is not narrow.",
     "trigger": "IB completes at 10:15 with price still inside prior value.",
     "strategy": "Intraday iron condor: short strikes beyond IB / prior VA / prior day extremes.",
     "stop": "Close the threatened side on a 30-min close beyond the IB or if its premium doubles.",
     "targets": "50-70% of credit by 14:30-15:00."},
    {"id": "C2", "group": "C", "name": "Wide-IB normal day",
     "context": "IB above 130% of its 10-session average; C period does not extend it.",
     "trigger": "C period (10:15-10:45) closes with no IB extension.",
     "strategy": "Iron condor with short strikes just outside the IB.",
     "stop": "30-min close outside the IB on either side.",
     "targets": "50-60% of credit or time exit at 15:00."},
    {"id": "C3", "group": "C", "name": "Multi-day balance - positional condor",
     "context": "Quiet 3+ session balance: overlapping value, flat POC, shrinking range.",
     "trigger": "Price near the composite POC with no breakout at IB completion.",
     "strategy": "Positional iron condor outside the balance (NIFTY 3-5 sessions, BANKNIFTY 2-3 weeks out).",
     "stop": "Daily close outside the composite VA or short strike near 0.40 delta.",
     "targets": "50% of max credit or exit the day before expiry."},
    {"id": "D1", "group": "D", "name": "Expiry pin - iron fly",
     "context": "Expiry day; price pinned near the highest-OI strike that matches the developing POC.",
     "trigger": "12:00-14:00 period close within half a strike of the pin.",
     "strategy": "Small iron fly at the pin strike.",
     "stop": "Price leaves the pin by more than one strike; out by 14:30 regardless.",
     "targets": "Theta into the afternoon; flat before the closing auction."},
]

SETUP_IDS = [s["id"] for s in SETUPS]
